spring:
  application:
    name: eureka
server:
  port: 1111
eureka:
  client:
#    registerWithEureka: true
#    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:2222/eureka/